# Generated by Django 4.0.3 on 2022-03-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
